# Generated by Django 2.2.7 on 2019-12-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flair',
            field=models.FileField(blank=True, upload_to='data/%Y%m%d%H%M/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='t1',
            field=models.FileField(blank=True, upload_to='data/%Y%m%d%H%M/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='t1ce',
            field=models.FileField(blank=True, upload_to='data/%Y%m%d%H%M/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='t2',
            field=models.FileField(blank=True, upload_to='data/%Y%m%d%H%M/'),
        ),
    ]
